### ISSUE TITLE
Extracted ground truth does not include feature model

### ISSUE THREAD

**Issue by theMichaelScheurer** [VariantSync/VEVOS_Extraction#1]
The .zip of the ground truth data of a commit does not contain feature-model.dimacs/variability-model.json when running extraction using the docker image. This was tested in linux (Ubuntu) and Windows 10 for busybox.
This bug seems to have been introduced in commit 347137e as extraction in 86e0cd0 does generate the files for me.

# Reproduction
- checkout main branch
- (empty extraction-results folder)
- run `./build-docker-image.sh` or `.\build-docker-image.bat`
- run `./start-extraction.sh busybox b35eef5383a4e7a6fb60fcf3833654a0bb2245e0` or `.\start-extraction.bat busybox b35eef5383a4e7a6fb60fcf3833654a0bb2245e0`
- .zip will be created for the commit but will not contain feature-model.dimacs/variability-model.json
  - (repeating this while checking out commit 86e0cd0 of VEVOS should lead to succesful extraction of the feature model)

**Comment by AlexanderSchultheiss** [comment]
I was able to reproduce the bug by following the instructions. I was also able to identify the bug by looking at 347137e. The [flag](https://github.com/VariantSync/VEVOS_Extraction/commit/347137e352be6adeff78f1f5f3c0fbf48750782d#diff-75330e0a9492c6a9c60f0c3346c60cc4586e820f57c4de66547df866faa3303fR109), which controls whether a feature model is to be extracted, is always set to false, because the name of the class does not match.

**Comment by AlexanderSchultheiss** [comment]
Hi @theMichaelScheurer could you please have a look at the [pull request](https://github.com/VariantSync/VEVOS_Extraction/pull/2) and review the bugfix?
